import { StyleSheet } from 'react-native';
import { TOKENS, LIGHT_COLORS } from '../constants/tokens';
import { useTheme } from '../hooks/useTheme';

export const getProfileStyles = (colors: typeof LIGHT_COLORS) =>
  StyleSheet.create({
    listContent: { padding: 24, paddingBottom: 140 },
    profileHeaderCard: {
      alignItems: 'stretch',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.muted,
      marginBottom: 8,
    },
    profileMainRow: { flexDirection: 'row-reverse', alignItems: 'center', width: '100%', paddingVertical: 8 },
    profileInfoColumn: { flex: 1, alignItems: 'flex-start' },
    profileMetaRow: { flexDirection: 'row-reverse', alignItems: 'center', marginTop: 6 },
    avatarCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: colors.brand.gold,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.brand.gold,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
      marginLeft: 16,
    },
    avatarText: { color: '#FFFFFF', fontSize: 28, fontWeight: 'bold', lineHeight: 34 },
    profileName: { fontSize: 18, fontWeight: 'bold', color: colors.text.primary, lineHeight: 24, textAlign: 'right' },
    profileTitle: {
      fontSize: 10,
      color: colors.brand.gold,
      fontWeight: '600',
      backgroundColor: 'rgba(0, 85, 165, 0.08)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: TOKENS.borderRadius.full,
      lineHeight: 14,
      overflow: 'hidden',
    },
    inlineStatsBox: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      marginRight: 10,
      backgroundColor: colors.background.input,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: TOKENS.borderRadius.full,
    },
    statVal: { fontSize: 11, fontWeight: 'bold', color: colors.text.primary, lineHeight: 14 },
    statLabel: { fontSize: 9, color: colors.text.secondary, marginRight: 4, lineHeight: 12 },
    profileEmail: { fontSize: 11, color: colors.text.secondary, marginTop: 6, lineHeight: 16, textAlign: 'right' },
    optionsCard: {
      backgroundColor: colors.background.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border.muted,
      padding: 16,
      marginTop: 8,
      marginBottom: 8,
    },
    optionsTitle: { fontSize: 12, fontWeight: 'bold', color: colors.brand.gold, textAlign: 'right', marginBottom: 12 },
    optionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border.muted,
    },
    lastOptionRow: { borderBottomWidth: 0, paddingBottom: 4 },
    optionLabel: { fontSize: 13, color: colors.text.primary },
    optionLabelRed: { fontSize: 13, color: '#DC2626', fontWeight: 'bold' },
    chevron: { fontSize: 18, color: colors.text.disabled, fontWeight: '600' },
    chevronRed: { fontSize: 18, color: '#DC2626', fontWeight: 'bold' },
    sectionTitle: { fontSize: 14, fontWeight: 'bold', color: colors.text.primary, alignSelf: 'flex-start', marginTop: 32, marginBottom: 8, lineHeight: 22 },
    emptyContainer: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 16 },
    emptyIconCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: 'rgba(0, 85, 165, 0.05)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
      borderWidth: 3,
      borderColor: colors.brand.gold,
    },
    emptyIconDot: { width: 20, height: 20, borderRadius: 10, backgroundColor: colors.brand.gold },
    emptyTitle: { fontSize: 16, fontWeight: 'bold', color: colors.text.primary, marginBottom: 8, lineHeight: 24 },
    emptyDescription: { fontSize: 12, color: colors.text.secondary, textAlign: 'center', lineHeight: 20 },
    tabContainer: { flexDirection: 'row-reverse', backgroundColor: colors.background.input, borderRadius: 24, padding: 4, marginTop: 28, marginBottom: 16 },
    tabToggle: { flex: 1, paddingVertical: 10, borderRadius: 20, alignItems: 'center' },
    tabToggleActive: { backgroundColor: colors.background.card, shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
    tabToggleText: { fontSize: 13, fontWeight: '600', color: colors.text.secondary },
    tabToggleTextActive: { color: colors.brand.gold, fontWeight: 'bold' },
    
    // Custom Dense Vector Icon styles
    optionRightContainer: { flexDirection: 'row', alignItems: 'center' },
    optionIconWrapper: { width: 24, height: 24, justifyContent: 'center', alignItems: 'center', marginLeft: 12 },
    emailIconBody: { width: 18, height: 12, borderWidth: 2.2, borderColor: colors.brand.gold, borderRadius: 2 },
    emailIconFlapLeft: { position: 'absolute', width: 8, height: 2.2, backgroundColor: colors.brand.gold, transform: [{ rotate: '30deg' }], top: 8.5, left: 4 },
    emailIconFlapRight: { position: 'absolute', width: 8, height: 2.2, backgroundColor: colors.brand.gold, transform: [{ rotate: '-30deg' }], top: 8.5, right: 4 },
    supportIconBubble: { width: 18, height: 13, borderWidth: 2.2, borderColor: colors.brand.gold, borderRadius: 3.5, position: 'relative' },
    supportIconTail: {
      position: 'absolute',
      width: 5,
      height: 5,
      borderWidth: 2.2,
      borderColor: colors.brand.gold,
      borderTopWidth: 0,
      borderRightWidth: 0,
      bottom: -3.5,
      right: 3,
      transform: [{ rotate: '-45deg' }],
      backgroundColor: 'transparent',
    },
    shieldIconContainer: { width: 18, height: 16, position: 'relative', alignItems: 'center', justifyContent: 'center' },
    shieldIconShape: { width: 14, height: 14, borderWidth: 2.2, borderColor: colors.brand.gold, borderBottomLeftRadius: 6, borderBottomRightRadius: 6, borderTopLeftRadius: 2.5, borderTopRightRadius: 2.5 },
    shieldIconLine: { position: 'absolute', width: 2.2, height: 6, backgroundColor: colors.brand.gold, top: 5 },
    infoIconCircle: { width: 17, height: 17, borderRadius: 8.5, borderWidth: 2.2, borderColor: colors.brand.gold, justifyContent: 'center', alignItems: 'center' },
    infoIconDot: { width: 2.5, height: 2.5, borderRadius: 1.25, backgroundColor: colors.brand.gold, marginBottom: 2 },
    infoIconLine: { width: 2.5, height: 4.5, backgroundColor: colors.brand.gold, borderRadius: 1 },
    deleteIconContainer: { width: 18, height: 16, position: 'relative', justifyContent: 'center', alignItems: 'center' },
    deleteIconCan: { width: 13, height: 11, borderWidth: 2.2, borderColor: '#DC2626', borderRadius: 2, marginTop: 2 },
    deleteIconLid: { position: 'absolute', width: 16, height: 2.2, backgroundColor: '#DC2626', top: 1, borderRadius: 1 },
    
    // Custom Vector Logout Icon styles
    logoutIconContainer: { width: 18, height: 16, position: 'relative', justifyContent: 'center', alignItems: 'center' },
    logoutIconDoor: { position: 'absolute', right: 2, top: 1, bottom: 1, width: 8, borderWidth: 2.2, borderColor: '#DC2626', borderLeftWidth: 0, borderTopRightRadius: 2, borderBottomRightRadius: 2 },
    logoutIconArrowStem: { position: 'absolute', left: 1, width: 10, height: 2.2, backgroundColor: '#DC2626' },
    logoutIconArrowHeadTop: { position: 'absolute', left: 1, width: 6, height: 2.2, backgroundColor: '#DC2626', transform: [{ rotate: '-45deg' }], top: 4.5 },
    logoutIconArrowHeadBottom: { position: 'absolute', left: 1, width: 6, height: 2.2, backgroundColor: '#DC2626', transform: [{ rotate: '45deg' }], bottom: 4.5 },
  });

export const useProfileStyles = () => {
  const { colors } = useTheme();
  return getProfileStyles(colors);
};

export const styles = getProfileStyles(LIGHT_COLORS);

